### ISSUE TITLE
python_requires >= 3.12

### ISSUE THREAD

**Issue by thangleiter** [MichaelSchneeberger/dataclass-abc#2]
Thanks for this neat little library! I have looked for something like it for some time.

Is it necessary to make the Python version so restrictive though? It works fine with 3.11 for me as is, and if `dataclass_transform` is also imported from `typing_extensions` on `ImportError`, 3.10 should also work.

https://github.com/MichaelSchneeberger/dataclass-abc/blob/df8720aa6c4bdd1e8c580f8c258946787c8beb12/dataclassabc/__init__.py#L5-L10

**Comment by MichaelSchneeberger** [comment]
Agreed. I've reverted the required Python version to 3.10 based on your suggestions. A new PyPI package version 0.0.10 has been released.

Thanks for the input.
